#.travis.yml

language: node_js
node_js:
  - '8.9.4'

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy -P prod --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
