#.travis.yml

language: node_js
node_js:
  - '10.15.1'

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false"  ]]; then ng build --prod; fi
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then ng build --configuration=staging; fi

after_success:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false"  ]]; then firebase deploy -P prod --token $FIREBASE_TOKEN; fi
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then firebase deploy -P staging --token $FIREBASE_TOKEN; fi

notifications:
  email:
    on_failure: change
    on_success: change
