export const froalaOptions = {
  // #general
  placeholderText: 'Describe your day ...',
  charCounterCount: false,
  // multiline: true,
  // scrollableContainer: '#my_scrollable_container',
  // htmlAllowedTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
  // fullPage: false,
  // #dimensions
  // height: 300,
  // heightMax: 500,
  // heightMin: 200,
  // width: 800,
  // indentMargin: 10,

  // #style
  colorsBackground: [
    '#61BD6D',
    '#1ABC9C',
    '#54ACD2',
    '#2C82C9',
    '#9365B8',
    '#475577',
    '#CCCCCC',
    '#41A85F',
    '#00A885',
    '#3D8EB9',
    '#2969B0',
    '#553982',
    '#28324E',
    '#000000',
    '#F7DA64',
    '#FBA026',
    '#EB6B56',
    '#E25041',
    '#A38F84',
    '#EFEFEF',
    '#FFFFFF',
    '#FAC51C',
    '#F37934',
    '#D14841',
    '#B8312F',
    '#7C706B',
    '#D1D5D8',
    'REMOVE'
  ],
  colorsText: [
    '#61BD6D',
    '#1ABC9C',
    '#54ACD2',
    '#2C82C9',
    '#9365B8',
    '#475577',
    '#CCCCCC',
    '#41A85F',
    '#00A885',
    '#3D8EB9',
    '#2969B0',
    '#553982',
    '#28324E',
    '#000000',
    '#F7DA64',
    '#FBA026',
    '#EB6B56',
    '#E25041',
    '#A38F84',
    '#EFEFEF',
    '#FFFFFF',
    '#FAC51C',
    '#F37934',
    '#D14841',
    '#B8312F',
    '#7C706B',
    '#D1D5D8',
    'REMOVE'
  ],
  // editorClass: 'custom-class',

  // #toolbar
  toolbarButtons: [
    'fullscreen',
    'bold',
    'italic',
    'underline',
    '|',
    'fontFamily',
    'fontSize',
    'color',
    'inlineStyle',
    'paragraphStyle',
    '|',
    'paragraphFormat',
    'align',
    'formatOL',
    'formatUL',
    'outdent',
    'indent',
    'quote',
    'insertLink',
    'insertImage',
    'insertTable',
    '|',
    'emoticons',
    'specialCharacters',
    'insertHR',
    '|',
    'print',
    'spellChecker',
    'help',
    '|',
    'undo',
    'redo'
  ],
  toolbarButtonsMD: [
    'fullscreen',
    'bold',
    'italic',
    'underline',
    'fontFamily',
    'fontSize',
    'color',
    '|',
    'paragraphFormat',
    'align',
    'formatOL',
    'formatUL',
    'insertLink',
    'insertImage',
    'insertTable',
    'undo',
    'redo'
  ],
  toolbarButtonsSM: [
    'fullscreen',
    'bold',
    'italic',
    'underline',
    'fontFamily',
    'fontSize',
    'color',
    '|',
    'paragraphFormat',
    'align',
    'formatOL',
    'formatUL',
    'insertLink',
    'insertImage',
    'insertTable',
    'undo',
    'redo'
  ],
  toolbarButtonsXS: [
    'bold',
    'italic',
    'fontFamily',
    'fontSize',
    'formatOL',
    'formatUL',
    'undo',
    'redo'
  ],
  // toolbarContainer: '#toolbarContainer',
  // toolbarInline: true,
  // toolbarBottom: false,
  // toolbarSticky: false,
  // toolbarStickyOffset: 50,
  // toolbarVisibleWithoutSelection: true,
  codeView: false,

  // #images
  // imageDefaultWidth: 200,
  // imageEditButtons: [
  //   'imageReplace',
  //   'imageAlign',
  //   'imageCaption',
  //   'imageRemove',
  //   '|',
  //   'imageLink',
  //   'linkOpen',
  //   'linkEdit',
  //   'linkRemove',
  //   '-',
  //   'imageDisplay',
  //   'imageStyle',
  //   'imageAlt',
  //   'imageSize'
  // ],
  // imageMaxSize: 1024 * 1024 * 10,
  // imageMinWidth: 16,
  imageMove: true,
  imagePaste: true,
  imageUpload: true,
  imageResizeWithPercent: true
};
